CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100),
  email VARCHAR(100),
  password VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sessions (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT,
  correct INT,
  total INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  module VARCHAR(50),
  game VARCHAR(50)
);

CREATE TABLE words (
  id INT PRIMARY KEY AUTO_INCREMENT,
  word VARCHAR(100),
  stress VARCHAR(100),
  tip VARCHAR(100)
);
INSERT INTO words (id, word, stress, tip) VALUES
(1,'presentation','pre-zen-TAY-shun','stress more on TAY'),
(2,'communication','kuh-myoo-nih-KAY-shun','stress more on KAY'),
(3,'collaboration','kuh-lab-uh-RAY-shun','stress more on RAY'),
(4,'negotiation','nih-goh-shee-AY-shun','stress more on AY'),
(5,'implementation','im-pluh-men-TAY-shun','stress more on TAY'),
(6,'opportunity','op-er-TYOO-nih-tee','stress more on TYOO'),
(7,'responsibility','rih-spon-sih-BIL-ih-tee','stress more on BIL'),
(8,'accountability','uh-kown-tuh-BIL-ih-tee','stress more on BIL'),
(9,'productivity','proh-duk-TIV-ih-tee','stress more on TIV'),
(10,'efficiency','ih-FISH-en-see','stress more on FISH'),
(11,'professionalism','pruh-FESH-uh-nuh-liz-um','stress more on FESH'),
(12,'leadership','LEE-der-ship','stress more on LEE'),
(13,'management','MAN-ij-ment','stress more on MAN'),
(14,'performance','per-FOR-mens','stress more on FOR'),
(15,'achievement','uh-CHEEV-ment','stress more on CHEEV'),
(16,'development','dih-VEL-up-ment','stress more on VEL'),
(17,'stakeholder','STAYK-hohl-der','stress more on STAYK'),
(18,'deliverable','dih-LIV-er-uh-bul','stress more on LIV'),
(19,'objective','ub-JEK-tiv','stress more on JEK'),
(20,'strategy','STRAT-uh-jee','stress more on STRAT'),
(21,'initiative','ih-NISH-ee-uh-tiv','stress more on NISH'),
(22,'innovation','in-uh-VAY-shun','stress more on VAY'),
(23,'sustainability','suh-stay-nuh-BIL-ih-tee','stress more on BIL'),
(24,'transparency','trans-PAIR-en-see','stress more on PAIR'),
(25,'perspective','per-SPEK-tiv','stress more on SPEK'),
(26,'facilitation','fuh-sil-ih-TAY-shun','stress more on TAY'),
(27,'prioritization','pry-or-ih-tih-ZAY-shun','stress more on ZAY'),
(28,'infrastructure','IN-fruh-struk-cher','stress more on IN'),
(29,'procurement','pruh-KYOOR-ment','stress more on KYOOR'),
(30,'compliance','kum-PLY-ens','stress more on PLY'),
(31,'confidentiality','kon-fih-den-shee-AL-ih-tee','stress more on AL'),
(32,'entrepreneurship','on-truh-pruh-NUR-ship','stress more on NUR'),
(33,'compensation','kom-pen-SAY-shun','stress more on SAY'),
(34,'recognition','rek-ug-NIH-shun','stress more on NIH'),
(35,'qualification','kwol-ih-fih-KAY-shun','stress more on KAY'),
(36,'evaluation','ih-val-yoo-AY-shun','stress more on AY'),
(37,'recommendation','rek-uh-men-DAY-shun','stress more on DAY'),
(38,'clarification','klair-ih-fih-KAY-shun','stress more on KAY'),
(39,'authorization','aw-thor-ih-ZAY-shun','stress more on ZAY'),
(40,'coordination','koh-or-dih-NAY-shun','stress more on NAY'),
(41,'documentation','dok-yoo-men-TAY-shun','stress more on TAY'),
(42,'consolidation','kun-sol-ih-DAY-shun','stress more on DAY'),
(43,'optimization','op-tih-mih-ZAY-shun','stress more on ZAY'),
(44,'integration','in-tih-GRAY-shun','stress more on GRAY'),
(45,'engagement','en-GAYJ-ment','stress more on GAYJ'),
(46,'retention','rih-TEN-shun','stress more on TEN'),
(47,'delegation','del-ih-GAY-shun','stress more on GAY'),
(48,'escalation','es-kuh-LAY-shun','stress more on LAY'),
(49,'articulate','ar-TIK-yoo-lit','stress more on TIK'),
(50,'competency','KOM-puh-ten-see','stress more on KOM'),
(51,'mentorship','MEN-tor-ship','stress more on MEN'),
(52,'networking','NET-wer-king','stress more on NET'),
(53,'feasibility','fee-zuh-BIL-ih-tee','stress more on BIL'),
(54,'scalability','skay-luh-BIL-ih-tee','stress more on BIL'),
(55,'reliability','rih-ly-uh-BIL-ih-tee','stress more on BIL'),
(56,'adaptability','uh-dap-tuh-BIL-ih-tee','stress more on BIL'),
(57,'vulnerability','vul-ner-uh-BIL-ih-tee','stress more on BIL'),
(58,'confidently','KON-fih-dent-lee','stress more on KON'),
(59,'professionally','pruh-FESH-uh-nuh-lee','stress more on FESH'),
(60,'effectively','ih-FEK-tiv-lee','stress more on FEK'),
(61,'efficiently','ih-FISH-ent-lee','stress more on FISH'),
(62,'proactively','proh-AK-tiv-lee','stress more on AK'),
(63,'collaboratively','kuh-LAB-uh-ruh-tiv-lee','stress more on LAB'),
(64,'constructively','kun-STRUK-tiv-lee','stress more on STRUK'),
(65,'comprehensively','kom-prih-HEN-siv-lee','stress more on HEN'),
(66,'strategically','struh-TEE-jih-klee','stress more on TEE'),
(67,'systematically','sis-tuh-MAT-ik-lee','stress more on MAT'),
(68,'quarterly','KWOR-ter-lee','stress more on KWOR'),
(69,'milestone','MYL-stohn','stress more on MYL'),
(70,'benchmark','BENCH-mark','stress more on BENCH'),
(71,'portfolio','port-FOH-lee-oh','stress more on FOH'),
(72,'agenda','uh-JEN-duh','stress more on JEN'),
(73,'protocol','PROH-tuh-kol','stress more on PROH'),
(74,'deadline','DED-lyne','stress more on DED'),
(75,'feedback','FEED-bak','stress more on FEED'),
(76,'workflow','WERK-floh','stress more on WERK'),
(77,'brainstorm','BRAYN-storm','stress more on BRAYN'),
(78,'onboarding','ON-bord-ing','stress more on ON'),
(79,'outsourcing','OWT-sor-sing','stress more on OWT'),
(80,'forecasting','FOR-kast-ing','stress more on FOR'),
(81,'budgeting','BUJ-ih-ting','stress more on BUJ'),
(82,'reporting','ri-PORT-ing','stress more on PORT'),
(83,'scheduling','SKED-yoo-ling','stress more on SKED'),
(84,'resolution','rez-uh-LOO-shun','stress more on LOO'),
(85,'transaction','tran-ZAK-shun','stress more on ZAK'),
(86,'allocation','al-uh-KAY-shun','stress more on KAY'),
(87,'assumption','uh-SUMP-shun','stress more on SUMP'),
(88,'projection','pruh-JEK-shun','stress more on JEK'),
(89,'conclusion','kun-KLOO-zhun','stress more on KLOO'),
(90,'assertion','uh-SER-shun','stress more on SER'),
(91,'discussion','dih-SKUSH-un','stress more on SKUSH'),
(92,'permission','per-MISH-un','stress more on MISH'),
(93,'requirement','rih-KWY-er-ment','stress more on KWY'),
(94,'adjustment','uh-JUST-ment','stress more on JUST'),
(95,'improvement','im-PROOV-ment','stress more on PROOV'),
(96,'clarify','KLAIR-ih-fy','stress more on KLAIR'),
(97,'summarize','SUM-uh-ryz','stress more on SUM'),
(98,'demonstrate','DEM-un-strayt','stress more on DEM'),
(99,'negotiate','nih-GOH-shee-ayt','stress more on GOH'),
(100,'collaborate','kuh-LAB-uh-rayt','stress more on LAB'),
(101,'facilitate','fuh-SIL-ih-tayt','stress more on SIL'),
(102,'communicate','kuh-MYOO-nih-kayt','stress more on MYOO'),
(103,'implement','IM-pluh-ment','stress more on IM');

CREATE TABLE math_game (
  id INT PRIMARY KEY AUTO_INCREMENT,
  question VARCHAR(100),
  option1 VARCHAR(50),
  option2 VARCHAR(50),
  option3 VARCHAR(50),
  option4 VARCHAR(50),
  answer VARCHAR(50)
);
INSERT INTO math_game (id,question,option1,option2,option3,option4,answer) VALUES
(1,'5 + 3 = ?','6','7','8','9','8'),
(2,'10 - 4 = ?','5','6','7','8','6'),
(3,'6 × 2 = ?','10','12','14','16','12'),
(4,'9 + 5 = ?','12','13','14','15','14'),
(5,'15 ÷ 3 = ?','3','4','5','6','5'),
(6,'12 + 8 = ?','18','19','20','21','20'),
(7,'7 × 6 = ?','40','42','44','46','42'),
(8,'18 ÷ 2 = ?','7','8','9','10','9'),
(9,'25 - 9 = ?','14','15','16','17','16'),
(10,'9 × 9 = ?','72','81','90','99','81'),
(11,'30 ÷ 5 = ?','5','6','7','8','6'),
(12,'14 + 6 = ?','18','19','20','21','20'),
(13,'16 - 7 = ?','7','8','9','10','9'),
(14,'8 × 4 = ?','30','32','34','36','32'),
(15,'45 ÷ 9 = ?','3','4','5','6','5'),
(16,'11 + 11 = ?','20','21','22','23','22'),
(17,'20 - 8 = ?','10','11','12','13','12'),
(18,'3 × 7 = ?','18','19','20','21','21'),
(19,'36 ÷ 6 = ?','5','6','7','8','6'),
(20,'50 - 25 = ?','20','22','25','30','25'),
(21,'13 + 9 = ?','20','21','22','23','22'),
(22,'4 × 8 = ?','30','32','34','36','32'),
(23,'64 ÷ 8 = ?','6','7','8','9','8'),
(24,'27 + 3 = ?','28','29','30','31','30'),
(25,'100 - 45 = ?','50','55','60','65','55');

CREATE TABLE memory_chain (
  id INT PRIMARY KEY AUTO_INCREMENT,
  sequence TEXT
);
INSERT INTO memory_chain (id, sequence) VALUES
(1,'["Lion","Tiger","Elephant","Monkey","Parrot"]'),
(2,'["Apple","Mango","Banana","Orange","Grape"]'),
(3,'["Red","Blue","Green","Yellow","Purple"]'),
(4,'["Chair","Table","Lamp","Book","Clock"]'),
(5,'["River","Forest","Mountain","Desert","Island"]'),
(6,'["Dog","Cat","Cow","Goat","Horse"]'),
(7,'["Pen","Book","Bag","Bottle","Shoes"]'),
(8,'["Sun","Moon","Star","Sky","Cloud"]'),
(9,'["Car","Bus","Train","Bike","Truck"]'),
(10,'["Bread","Milk","Butter","Cheese","Egg"]'),
(11,'["Doctor","Teacher","Engineer","Farmer","Chef"]'),
(12,'["Phone","Laptop","Tablet","Camera","Speaker"]'),
(13,'["India","USA","Japan","Germany","Brazil"]'),
(14,'["Gold","Silver","Bronze","Iron","Copper"]'),
(15,'["Summer","Winter","Rainy","Spring","Autumn"]'),
(16,'["Circle","Square","Triangle","Rectangle","Oval"]'),
(17,'["Run","Jump","Walk","Climb","Swim"]'),
(18,'["Happy","Sad","Angry","Excited","Calm"]'),
(19,'["North","South","East","West","Center"]'),
(20,'["Water","Fire","Earth","Air","Space"]');

CREATE TABLE questions (
  id INT PRIMARY KEY AUTO_INCREMENT,
  type VARCHAR(50),
  question TEXT
);
INSERT INTO questions (id, type, question) VALUES
(1,'mock','Tell me about yourself and your professional background.'),
(2,'mock','What are your three greatest strengths and why?'),
(3,'mock','What is your biggest weakness and what are you doing to improve it?'),
(4,'mock','Why should we hire you over other candidates?'),
(5,'mock','Where do you see yourself in five years?'),
(6,'mock','Describe a major challenge you faced at work and how you overcame it.'),
(7,'mock','How do you handle working under pressure or tight deadlines?'),
(8,'mock','Give an example of a time you worked well in a team.'),
(9,'mock','What motivates you in your work every day?'),
(10,'mock','Why are you looking to leave your current position?'),
(11,'mock','What are your salary expectations for this role?'),
(12,'mock','How do you prioritize tasks when you have multiple deadlines at the same time?'),
(13,'mock','Tell me about a time you demonstrated leadership skills.'),
(14,'mock','How do you handle conflict or disagreement with a coworker?'),
(15,'mock','What do you know about our company and why do you want to work here?'),
(16,'mock','Describe your ideal work environment.'),
(17,'mock','What is your greatest professional achievement so far?'),
(18,'mock','How do you keep yourself updated with industry trends and news?'),
(19,'mock','Tell me about a time you failed and what you learned from it.'),
(20,'mock','Do you prefer working independently or in a team, and why?'),
(21,'mock','Describe a time when you had to adapt quickly to a change at work.'),
(22,'mock','Tell me about a time you went above and beyond for a client or colleague.'),
(23,'mock','How do you manage your time and stay organised during a busy week?'),
(24,'mock','Give an example of when you had to make a difficult decision at work.'),
(25,'mock','Tell me about a time you disagreed with your manager and how you handled it.'),

-- 🔹 SMALL TALK (51–75)
(51,'smalltalk','How has your week been going so far?'),
(52,'smalltalk','Did you have a good weekend? What did you get up to?'),
(53,'smalltalk','Have you been working on any interesting projects lately?'),
(54,'smalltalk','What do you enjoy doing outside of work?'),
(55,'smalltalk','Have you travelled anywhere interesting recently?'),
(56,'smalltalk','What kind of industry events or conferences do you attend?'),
(57,'smalltalk','Have you read any good books or podcasts lately?'),
(58,'smalltalk','How long have you been working in your current role?'),
(59,'smalltalk','What got you interested in your field of work?'),
(60,'smalltalk','What are you looking forward to today?'),
(61,'smalltalk','Do you prefer working from home or office?'),
(62,'smalltalk','What is your favorite way to relax after work?'),
(63,'smalltalk','Do you enjoy team activities or solo work more?'),
(64,'smalltalk','What motivates you to stay productive?'),
(65,'smalltalk','Do you like learning new skills regularly?'),
(66,'smalltalk','What is your favorite subject or topic?'),
(67,'smalltalk','How do you usually start your day?'),
(68,'smalltalk','What kind of music do you enjoy?'),
(69,'smalltalk','Do you like traveling? Where would you go next?'),
(70,'smalltalk','How do you manage stress?'),
(71,'smalltalk','What hobbies do you have?'),
(72,'smalltalk','Do you like reading books? Which type?'),
(73,'smalltalk','What is your favorite movie or show?'),
(74,'smalltalk','Do you prefer coffee or tea?'),
(75,'smalltalk','What makes a good day for you?'),

-- 🔹 PRESENTATION (101–125)
(101,'presentation','Give a 60-second introduction of yourself to a hiring manager.'),
(102,'presentation','Present your greatest professional achievement in two minutes.'),
(103,'presentation','Pitch a new product idea to investors.'),
(104,'presentation','Explain a complex topic to a non-expert audience.'),
(105,'presentation','Describe your career vision for next five years.'),
(106,'presentation','Explain your favorite subject in simple terms.'),
(107,'presentation','Present a problem and its solution.'),
(108,'presentation','Talk about a successful project you completed.'),
(109,'presentation','Describe a leadership experience.'),
(110,'presentation','Explain why teamwork is important.'),
(111,'presentation','Present a product you like and why.'),
(112,'presentation','Explain a recent trend in technology.'),
(113,'presentation','Describe your biggest learning experience.'),
(114,'presentation','Talk about time management strategies.'),
(115,'presentation','Explain importance of communication skills.'),
(116,'presentation','Describe your strengths in presentation.'),
(117,'presentation','Present your daily routine effectively.'),
(118,'presentation','Explain a failure and lessons learned.'),
(119,'presentation','Describe your role model.'),
(120,'presentation','Explain how to stay motivated.'),
(121,'presentation','Talk about importance of leadership.'),
(122,'presentation','Explain a concept you recently learned.'),
(123,'presentation','Describe your dream job.'),
(124,'presentation','Explain importance of discipline.'),
(125,'presentation','Talk about future goals.');

CREATE TABLE responses (
  id INT PRIMARY KEY AUTO_INCREMENT,
  question_id INT,
  session_type VARCHAR(50),
  user_answer TEXT,
  feedback TEXT,
  score INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE storytelling (
  id INT PRIMARY KEY AUTO_INCREMENT,
  theme VARCHAR(50),
  template TEXT,
  blanks TEXT
);
INSERT INTO storytelling (id, theme, template, blanks) VALUES

(1,'jungle','One morning, a [ADJECTIVE] explorer named [NAME] entered a [ADJECTIVE] jungle. Suddenly, a [ANIMAL] jumped out and made a [SOUND] noise. The explorer grabbed a [OBJECT] and ran towards a [ADJECTIVE] river as fast as their [BODY_PART] could carry them!',
'[{"slot":"[ADJECTIVE]"},{"slot":"[NAME]"},{"slot":"[ADJECTIVE]"},{"slot":"[ANIMAL]"},{"slot":"[SOUND]"},{"slot":"[OBJECT]"},{"slot":"[ADJECTIVE]"},{"slot":"[BODY_PART]"}]'),

(2,'space','Commander [NAME] launched a [ADJECTIVE] rocket towards planet [PLANET_NAME]. The crew ate [FOOD] for dinner and played [SPORT] in zero gravity.',
'[{"slot":"[NAME]"},{"slot":"[ADJECTIVE]"},{"slot":"[PLANET_NAME]"},{"slot":"[FOOD]"},{"slot":"[SPORT]"}]'),

(3,'school','Today was a [ADJECTIVE] day at school. My teacher, [NAME], gave us a [ADJECTIVE] assignment. Suddenly, a [ANIMAL] entered the classroom and made a [SOUND] noise! Everyone started laughing while I dropped my [OBJECT]. Later, we ran to the playground and played using our [BODY_PART]. It was truly a [ADJECTIVE] day!',
'[{"slot":"[ADJECTIVE]"},{"slot":"[NAME]"},{"slot":"[ADJECTIVE]"},{"slot":"[ANIMAL]"},{"slot":"[SOUND]"},{"slot":"[OBJECT]"},{"slot":"[BODY_PART]"},{"slot":"[ADJECTIVE]"}]'),

(4,'kingdom','In a [ADJECTIVE] magical kingdom, there lived a brave hero named [NAME]. One day, a [ANIMAL] appeared and made a [SOUND] noise. The hero picked up a [OBJECT] and used their [BODY_PART] to fight. With a [ADJECTIVE] move, they saved the kingdom and everyone called it a [ADJECTIVE] victory!',
'[{"slot":"[ADJECTIVE]"},{"slot":"[NAME]"},{"slot":"[ANIMAL]"},{"slot":"[SOUND]"},{"slot":"[OBJECT]"},{"slot":"[BODY_PART]"},{"slot":"[ADJECTIVE]"},{"slot":"[ADJECTIVE]"}]'),

(5,'kingdom','In a [ADJECTIVE] magical kingdom, there lived a brave hero named [NAME]. One day, a [ANIMAL] appeared and made a [SOUND] noise. The hero picked up a [OBJECT] and used their [BODY_PART] to fight. With a [ADJECTIVE] move, they saved the kingdom and everyone called it a [ADJECTIVE] victory!',
'[{"slot":"[ADJECTIVE]"},{"slot":"[NAME]"},{"slot":"[ANIMAL]"},{"slot":"[SOUND]"},{"slot":"[OBJECT]"},{"slot":"[BODY_PART]"},{"slot":"[ADJECTIVE]"},{"slot":"[ADJECTIVE]"}]'),

(6,'school','My [ADJECTIVE] friend [NAME] brought a [OBJECT] to school today. During class, a [ANIMAL] suddenly appeared and made a [SOUND] noise. Everyone used their [BODY_PART] to cover their ears. It turned into a very [ADJECTIVE] moment!',
'[{"slot":"[ADJECTIVE]"},{"slot":"[NAME]"},{"slot":"[OBJECT]"},{"slot":"[ANIMAL]"},{"slot":"[SOUND]"},{"slot":"[BODY_PART]"},{"slot":"[ADJECTIVE]"}]'),

(7,'school','At school, we had a [ADJECTIVE] competition. My partner [NAME] used a [OBJECT] and made a [SOUND] noise. Suddenly, a [ANIMAL] joined us and everyone used their [BODY_PART] to cheer. It was a [ADJECTIVE] event!',
'[{"slot":"[ADJECTIVE]"},{"slot":"[NAME]"},{"slot":"[OBJECT]"},{"slot":"[SOUND]"},{"slot":"[ANIMAL]"},{"slot":"[BODY_PART]"},{"slot":"[ADJECTIVE]"}]'),

(8,'school','During lunch, I saw a [ADJECTIVE] [ANIMAL] near the cafeteria. My friend [NAME] dropped a [OBJECT] and it made a [SOUND] noise. We ran using our [BODY_PART] and had a [ADJECTIVE] time!',
'[{"slot":"[ADJECTIVE]"},{"slot":"[ANIMAL]"},{"slot":"[NAME]"},{"slot":"[OBJECT]"},{"slot":"[SOUND]"},{"slot":"[BODY_PART]"},{"slot":"[ADJECTIVE]"}]'),

(9,'school','Our teacher [NAME] gave us a [ADJECTIVE] project. I used a [OBJECT] while a [ANIMAL] made a [SOUND] noise. I raised my [BODY_PART] and everyone said it was a [ADJECTIVE] idea!',
'[{"slot":"[NAME]"},{"slot":"[ADJECTIVE]"},{"slot":"[OBJECT]"},{"slot":"[ANIMAL]"},{"slot":"[SOUND]"},{"slot":"[BODY_PART]"},{"slot":"[ADJECTIVE]"}]'),

(10,'kingdom','In a [ADJECTIVE] kingdom, a wizard named [NAME] used a [OBJECT]. Suddenly, a [ANIMAL] made a [SOUND] noise. The wizard used their [BODY_PART] to cast a [ADJECTIVE] spell!',
'[{"slot":"[ADJECTIVE]"},{"slot":"[NAME]"},{"slot":"[OBJECT]"},{"slot":"[ANIMAL]"},{"slot":"[SOUND]"},{"slot":"[BODY_PART]"},{"slot":"[ADJECTIVE]"}]'),

(11,'kingdom','A [ADJECTIVE] dragon guarded the kingdom. Hero [NAME] picked a [OBJECT] and made a [SOUND] noise. Using their [BODY_PART], they defeated it in a [ADJECTIVE] way!',
'[{"slot":"[ADJECTIVE]"},{"slot":"[NAME]"},{"slot":"[OBJECT]"},{"slot":"[SOUND]"},{"slot":"[BODY_PART]"},{"slot":"[ADJECTIVE]"}]'),

(12,'kingdom','In a [ADJECTIVE] castle, princess [NAME] saw a [ANIMAL]. It made a [SOUND] noise while holding a [OBJECT]. She used her [BODY_PART] and saved the day in a [ADJECTIVE] way!',
'[{"slot":"[ADJECTIVE]"},{"slot":"[NAME]"},{"slot":"[ANIMAL]"},{"slot":"[SOUND]"},{"slot":"[OBJECT]"},{"slot":"[BODY_PART]"},{"slot":"[ADJECTIVE]"}]'),

(13,'kingdom','The [ADJECTIVE] king [NAME] had a [OBJECT]. One day, a [ANIMAL] made a [SOUND] noise. The king used his [BODY_PART] and declared a [ADJECTIVE] celebration!',
'[{"slot":"[ADJECTIVE]"},{"slot":"[NAME]"},{"slot":"[OBJECT]"},{"slot":"[ANIMAL]"},{"slot":"[SOUND]"},{"slot":"[BODY_PART]"},{"slot":"[ADJECTIVE]"}]'),

(14,'jungle','In a [ADJECTIVE] jungle, a traveler named [NAME] found a [OBJECT]. Suddenly, a [ANIMAL] made a [SOUND] noise. The traveler used their [BODY_PART] and had a [ADJECTIVE] adventure!',
'[{"slot":"[ADJECTIVE]"},{"slot":"[NAME]"},{"slot":"[OBJECT]"},{"slot":"[ANIMAL]"},{"slot":"[SOUND]"},{"slot":"[BODY_PART]"},{"slot":"[ADJECTIVE]"}]'),

(15,'jungle','A [ADJECTIVE] explorer named [NAME] walked through the jungle. A [ANIMAL] appeared and made a [SOUND] noise. The explorer grabbed a [OBJECT] and used their [BODY_PART] to escape in a [ADJECTIVE] way!',
'[{"slot":"[ADJECTIVE]"},{"slot":"[NAME]"},{"slot":"[ANIMAL]"},{"slot":"[SOUND]"},{"slot":"[OBJECT]"},{"slot":"[BODY_PART]"},{"slot":"[ADJECTIVE]"}]'),

(16,'jungle','Deep in the jungle, a [ADJECTIVE] [ANIMAL] started following [NAME]. It suddenly made a loud [SOUND] noise while chasing a shiny [OBJECT]. Thinking quickly, [NAME] used their [BODY_PART] to escape safely and later shared a truly [ADJECTIVE] story!',
'[{"slot":"[ADJECTIVE]"},{"slot":"[ANIMAL]"},{"slot":"[NAME]"},{"slot":"[SOUND]"},{"slot":"[OBJECT]"},{"slot":"[BODY_PART]"},{"slot":"[ADJECTIVE]"}]'),

(17,'jungle','A [ADJECTIVE] day in the jungle turned exciting when [NAME] saw a [ANIMAL]. It made a [SOUND] noise near a [OBJECT]. Using their [BODY_PART], [NAME] reacted quickly and had a [ADJECTIVE] experience!',
'[{"slot":"[ADJECTIVE]"},{"slot":"[NAME]"},{"slot":"[ANIMAL]"},{"slot":"[SOUND]"},{"slot":"[OBJECT]"},{"slot":"[BODY_PART]"},{"slot":"[ADJECTIVE]"}]'),

(18,'space','In space, astronaut [NAME] saw a [ADJECTIVE] planet. Suddenly, a [ANIMAL] floated by and made a [SOUND] noise. They used a [OBJECT] and their [BODY_PART] to explore in a [ADJECTIVE] way!',
'[{"slot":"[NAME]"},{"slot":"[ADJECTIVE]"},{"slot":"[ANIMAL]"},{"slot":"[SOUND]"},{"slot":"[OBJECT]"},{"slot":"[BODY_PART]"},{"slot":"[ADJECTIVE]"}]'),

(19,'space','A [ADJECTIVE] spaceship carried [NAME] to a new galaxy. A [ANIMAL] made a [SOUND] noise while holding a [OBJECT]. Using their [BODY_PART], they survived in a [ADJECTIVE] way!',
'[{"slot":"[ADJECTIVE]"},{"slot":"[NAME]"},{"slot":"[ANIMAL]"},{"slot":"[SOUND]"},{"slot":"[OBJECT]"},{"slot":"[BODY_PART]"},{"slot":"[ADJECTIVE]"}]'),

(20,'space','Commander [NAME] landed on a [ADJECTIVE] planet. A [ANIMAL] appeared and made a [SOUND] noise. With a [OBJECT] and their [BODY_PART], they completed a [ADJECTIVE] mission!',
'[{"slot":"[NAME]"},{"slot":"[ADJECTIVE]"},{"slot":"[ANIMAL]"},{"slot":"[SOUND]"},{"slot":"[OBJECT]"},{"slot":"[BODY_PART]"},{"slot":"[ADJECTIVE]"}]'),

(21,'space','In a [ADJECTIVE] galaxy, pilot [NAME] found a [OBJECT]. Suddenly, a [ANIMAL] made a [SOUND] noise. Using their [BODY_PART], they had a [ADJECTIVE] adventure in space!',
'[{"slot":"[ADJECTIVE]"},{"slot":"[NAME]"},{"slot":"[OBJECT]"},{"slot":"[ANIMAL]"},{"slot":"[SOUND]"},{"slot":"[BODY_PART]"},{"slot":"[ADJECTIVE]"}]');

CREATE TABLE wordquiz (
  id INT PRIMARY KEY AUTO_INCREMENT,
  category VARCHAR(50),
  question TEXT,
  option1 VARCHAR(100),
  option2 VARCHAR(100),
  option3 VARCHAR(100),
  option4 VARCHAR(100),
  correct_answer VARCHAR(100)
);
INSERT INTO wordquiz VALUES
(2,'Science','What planet is closest to the Sun?','Venus','Mercury','Mars','Earth','mercury'),
(3,'Science','What gas do plants absorb from the air?','Oxygen','Nitrogen','Carbon Dioxide','Hydrogen','carbon dioxide'),
(4,'Science','What is the powerhouse of the cell?','Nucleus','Ribosome','Mitochondria','Vacuole','mitochondria'),
(5,'Science','How many bones are in the adult human body?','206','196','186','216','206'),
(6,'Science','What force keeps us on the ground?','Magnetism','Friction','Gravity','Tension','gravity'),
(7,'Science','What is the chemical symbol for water?','WO','H2O','HO2','W2O','h2o'),
(8,'Science','What is the speed of light?','300,000 km/s','150,000 km/s','450,000 km/s','100,000 km/s','300,000 km/s'),
(9,'Science','Which planet is known as the Red Planet?','Venus','Jupiter','Mars','Saturn','mars'),
(10,'Science','What is the boiling point of water in Celsius?','90','95','100','110','100'),
(11,'Science','How many chambers does the human heart have?','2','3','4','5','4'),

(12,'Agriculture','Which nutrient is most important for leaf growth?','Potassium','Phosphorus','Nitrogen','Calcium','nitrogen'),
(13,'Agriculture','What is the process of watering crops called?','Irrigation','Cultivation','Harvesting','Ploughing','irrigation'),
(14,'Agriculture','Which soil type is best for growing crops?','Sandy','Loamy','Clay','Rocky','loamy'),
(15,'Agriculture','What tool is used to plough fields?','Sickle','Tractor','Harrow','Plough','plough'),
(16,'Agriculture','Which crop is known as the golden fibre?','Cotton','Jute','Silk','Wool','jute'),
(17,'Agriculture','What is growing two crops together called?','Mixed cropping','Crop rotation','Monoculture','Intercropping','intercropping'),
(18,'Agriculture','Which vitamin is produced by sunlight on skin?','Vitamin A','Vitamin B','Vitamin C','Vitamin D','vitamin d'),
(19,'Agriculture','What is the main source of water for crops in India?','Rivers','Rainwater','Groundwater','Lakes','rainwater'),
(20,'Agriculture','Which crop is India the largest producer of?','Rice','Wheat','Sugarcane','Cotton','sugarcane'),
(21,'Agriculture','What is organic farming?','Using chemicals','Using natural methods','Using machines','Using irrigation','using natural methods'),
(22,'Agriculture','Which season is suitable for growing rice?','Winter','Summer','Monsoon','Spring','monsoon'),
(23,'Agriculture','What is the practice of growing fish and crops together called?','Mixed farming','Aquaculture','Rice-fish farming','Sericulture','rice-fish farming'),

(24,'Politics','Who is the head of government in India?','President','Prime Minister','Governor','Speaker','prime minister'),
(25,'Politics','How many members are in the Lok Sabha?','543','545','552','500','543'),
(26,'Politics','What does UN stand for?','United Nations','Universal Network','United Nationals','Union Nations','united nations'),
(27,'Politics','Which article abolishes untouchability in India?','Article 14','Article 17','Article 21','Article 32','article 17'),
(28,'Politics','Who was the first Prime Minister of India?','Sardar Patel','B.R. Ambedkar','Jawaharlal Nehru','Rajendra Prasad','jawaharlal nehru'),
(29,'Politics','What is the upper house of Indian Parliament called?','Lok Sabha','Rajya Sabha','Vidhan Sabha','Gram Sabha','rajya sabha'),
(30,'Politics','How many states are in India?','26','28','29','30','28'),
(31,'Politics','Who appoints the Prime Minister of India?','Speaker','Chief Justice','President','Vice President','president'),
(32,'Politics','What is the minimum age to vote in India?','16','18','21','25','18'),
(33,'Politics','Which body interprets the Constitution of India?','Parliament','Cabinet','Supreme Court','President','supreme court'),
(34,'Politics','What is the term of Lok Sabha?','4 years','5 years','6 years','3 years','5 years'),
(35,'Politics','Where is the Indian Parliament located?','Mumbai','Chennai','Kolkata','New Delhi','new delhi'),

(36,'Technology','What does AI stand for?','Automated Intelligence','Artificial Intelligence','Applied Intelligence','Advanced Interface','artificial intelligence'),
(37,'Technology','Which company made the Android operating system?','Apple','Microsoft','Google','Samsung','google'),
(38,'Technology','What does HTML stand for?','Hyper Text Markup Language','High Text Machine Language','Hyper Transfer Markup Link','Home Text Markup Language','hyper text markup language'),
(39,'Technology','What is the brain of a computer called?','RAM','Hard Disk','CPU','Monitor','cpu'),
(40,'Technology','Which language is used to style web pages?','Python','Java','CSS','SQL','css'),
(41,'Technology','What does GPS stand for?','General Positioning System','Global Positioning System','Ground Positioning Signal','Global Pointer System','global positioning system'),
(42,'Technology','What does RAM stand for?','Read Access Memory','Random Access Memory','Rapid Access Memory','Read And Memory','random access memory'),
(43,'Technology','Which programming language is used for web development?','Python','JavaScript','C++','Assembly','javascript'),
(44,'Technology','What is the full form of PDF?','Printed Document Format','Portable Document Format','Public Document File','Private Data Format','portable document format'),
(45,'Technology','Which company developed the Python language?','Google','Microsoft','Guido van Rossum','Apple','guido van rossum'),
(46,'Technology','What does USB stand for?','Universal Serial Bus','Ultra Speed Bus','Unified System Board','Universal System Base','universal serial bus'),
(47,'Technology','What is the most used search engine in the world?','Bing','Yahoo','Google','DuckDuckGo','google'),

(48,'History','In which year did India gain independence?','1945','1947','1950','1942','1947'),
(49,'History','Who built the Taj Mahal?','Akbar','Humayun','Shah Jahan','Aurangzeb','shah jahan'),
(50,'History','Which battle marked the beginning of British rule in India?','Battle of Panipat','Battle of Plassey','Battle of Buxar','Battle of Haldighati','battle of plassey'),
(51,'History','Who gave the slogan Do or Die?','Nehru','Tilak','Subhash Chandra Bose','Mahatma Gandhi','mahatma gandhi'),
(52,'History','The French Revolution began in which year?','1776','1789','1799','1804','1789'),
(53,'History','Who was the first President of the United States?','Abraham Lincoln','Thomas Jefferson','George Washington','John Adams','george washington'),
(54,'History','Who wrote the Indian National Anthem?','Bankim Chandra','Rabindranath Tagore','Subhash Chandra Bose','Sarojini Naidu','rabindranath tagore'),
(55,'History','In which year was the Constitution of India adopted?','1947','1948','1949','1950','1949'),
(56,'History','Who is known as the Iron Man of India?','Nehru','Rajendra Prasad','Sardar Patel','Bhagat Singh','sardar patel'),
(57,'History','Which civilization is the oldest in the world?','Greek','Roman','Mesopotamian','Egyptian','mesopotamian'),
(58,'History','When did World War 2 end?','1943','1944','1945','1946','1945'),
(59,'History','Who was the first person to walk on the Moon?','Buzz Aldrin','Neil Armstrong','Yuri Gagarin','Michael Collins','neil armstrong'),

(60,'Geography','What is the longest river in the world?','Amazon','Yangtze','Nile','Ganges','nile'),
(61,'Geography','Which is the largest continent?','Africa','North America','Europe','Asia','asia'),
(62,'Geography','What is the capital of Australia?','Sydney','Melbourne','Canberra','Brisbane','canberra'),
(63,'Geography','Which ocean is the largest?','Atlantic','Indian','Arctic','Pacific','pacific'),
(64,'Geography','Mount Everest is in which mountain range?','Alps','Andes','Himalayas','Rockies','himalayas'),
(65,'Geography','Which country has the most natural lakes?','Russia','USA','Brazil','Canada','canada'),
(66,'Geography','What is the smallest country in the world?','Monaco','Nauru','Vatican City','San Marino','vatican city'),
(67,'Geography','Which is the largest desert in the world?','Sahara','Arabian','Gobi','Antarctic','antarctic'),
(68,'Geography','What is the capital of Japan?','Osaka','Kyoto','Tokyo','Hiroshima','tokyo'),
(69,'Geography','Which river flows through Egypt?','Amazon','Congo','Nile','Niger','nile'),
(70,'Geography','Which is the tallest waterfall in the world?','Niagara','Victoria','Angel Falls','Iguazu','angel falls'),
(71,'Geography','What is the capital of Brazil?','Rio de Janeiro','Sao Paulo','Brasilia','Salvador','brasilia'),

(72,'Sports','How many players are in a football team on the field?','9','10','11','12','11'),
(73,'Sports','Which country invented cricket?','Australia','India','England','South Africa','england'),
(74,'Sports','How many rings are on the Olympic flag?','4','5','6','7','5'),
(75,'Sports','In which sport is love used for zero?','Cricket','Tennis','Badminton','Squash','tennis'),
(76,'Sports','Who has won the most Grand Slam tennis titles?','Roger Federer','Rafael Nadal','Novak Djokovic','Pete Sampras','novak djokovic'),
(77,'Sports','How many points is a touchdown worth?','3','6','7','2','6'),
(78,'Sports','Which country has won the most FIFA World Cups?','Germany','Argentina','Italy','Brazil','brazil'),
(79,'Sports','How many players are on a basketball team on court?','4','5','6','7','5'),
(80,'Sports','In which city were the first modern Olympic Games held?','Rome','Paris','Athens','London','athens'),
(81,'Sports','What is the national sport of Japan?','Judo','Karate','Sumo','Kendo','sumo'),
(82,'Sports','How long is a standard marathon in kilometers?','40','42.195','44','38','42.195'),
(83,'Sports','Which Indian cricketer is known as the God of Cricket?','Virat Kohli','MS Dhoni','Sachin Tendulkar','Rohit Sharma','sachin tendulkar'),

(84,'Health','How many hours of sleep do adults need per night?','4 to 5','6 to 7','7 to 9','10 to 12','7 to 9'),
(85,'Health','Which vitamin does sunlight provide?','Vitamin A','Vitamin B','Vitamin C','Vitamin D','vitamin d'),
(86,'Health','What is the normal human body temperature in Celsius?','35','36','37','38','37'),
(87,'Health','Which organ pumps blood through the body?','Lungs','Liver','Kidney','Heart','heart'),
(88,'Health','Which food group gives the most energy?','Proteins','Fats','Carbohydrates','Vitamins','carbohydrates'),
(89,'Health','How many times does a healthy heart beat per minute?','40 to 50','60 to 100','110 to 130','30 to 40','60 to 100'),
(90,'Health','Which vitamin helps in blood clotting?','Vitamin A','Vitamin C','Vitamin D','Vitamin K','vitamin k'),
(91,'Health','What is the largest organ of the human body?','Brain','Liver','Skin','Lungs','skin'),
(92,'Health','How much water should an adult drink per day?','1 litre','2 litres','3 litres','4 litres','2 litres'),
(93,'Health','Which mineral is most important for strong bones?','Iron','Zinc','Calcium','Magnesium','calcium'),
(94,'Health','What does BMI stand for?','Body Mass Index','Blood Mass Index','Body Muscle Index','Bone Mass Index','body mass index');