-- ═══════════════════════════════════════════════════════════════
--  voice_assist — Full Database Setup
--  Run ONCE in MySQL command client:
--    SOURCE C:/full/path/to/voice_assist_fixed/database/schema.sql;
-- ═══════════════════════════════════════════════════════════════

CREATE DATABASE IF NOT EXISTS voice_assist;
USE voice_assist;

CREATE TABLE IF NOT EXISTS questions (
    id       INT AUTO_INCREMENT PRIMARY KEY,
    type     VARCHAR(50) NOT NULL,
    question TEXT        NOT NULL
);

CREATE TABLE IF NOT EXISTS responses (
    id           INT AUTO_INCREMENT PRIMARY KEY,
    question_id  INT,
    session_type VARCHAR(50),
    user_answer  TEXT,
    feedback     TEXT,
    score        INT DEFAULT 0,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ═══════════════════════════════════════════════════════════════
--  MOCK INTERVIEW QUESTIONS — 50
-- ═══════════════════════════════════════════════════════════════
INSERT INTO questions (type, question) VALUES
('mock', 'Tell me about yourself and your professional background.'),
('mock', 'What are your three greatest strengths and why?'),
('mock', 'What is your biggest weakness and what are you doing to improve it?'),
('mock', 'Why should we hire you over other candidates?'),
('mock', 'Where do you see yourself in five years?'),
('mock', 'Describe a major challenge you faced at work and how you overcame it.'),
('mock', 'How do you handle working under pressure or tight deadlines?'),
('mock', 'Give an example of a time you worked well in a team.'),
('mock', 'What motivates you in your work every day?'),
('mock', 'Why are you looking to leave your current position?'),
('mock', 'What are your salary expectations for this role?'),
('mock', 'How do you prioritize tasks when you have multiple deadlines at the same time?'),
('mock', 'Tell me about a time you demonstrated leadership skills.'),
('mock', 'How do you handle conflict or disagreement with a coworker?'),
('mock', 'What do you know about our company and why do you want to work here?'),
('mock', 'Describe your ideal work environment.'),
('mock', 'What is your greatest professional achievement so far?'),
('mock', 'How do you keep yourself updated with industry trends and news?'),
('mock', 'Tell me about a time you failed and what you learned from it.'),
('mock', 'Do you prefer working independently or in a team, and why?'),
('mock', 'Describe a time when you had to adapt quickly to a change at work.'),
('mock', 'Tell me about a time you went above and beyond for a client or colleague.'),
('mock', 'How do you manage your time and stay organised during a busy week?'),
('mock', 'Give an example of when you had to make a difficult decision at work.'),
('mock', 'Tell me about a time you disagreed with your manager and how you handled it.'),
('mock', 'How would your previous colleagues describe your work style?'),
('mock', 'What skills are you currently developing or learning?'),
('mock', 'Describe a time when you had to deliver bad news to someone at work.'),
('mock', 'Tell me about a project you are most proud of and your role in it.'),
('mock', 'How do you handle feedback or criticism from others?'),
('mock', 'Give an example of how you have improved a process or system at work.'),
('mock', 'Tell me about a time you had to meet a very tight deadline.'),
('mock', 'How do you build relationships with new colleagues or clients?'),
('mock', 'Describe a situation where you showed initiative without being asked.'),
('mock', 'Tell me about a time you had to manage multiple stakeholders with different needs.'),
('mock', 'How do you deal with a team member who is not performing well?'),
('mock', 'What strategies do you use to stay productive when working remotely?'),
('mock', 'Describe a time when you had to learn a new skill very quickly.'),
('mock', 'Tell me about a time you successfully persuaded someone to see your point of view.'),
('mock', 'How do you ensure the quality of your work before submitting or presenting it?'),
('mock', 'Give an example of a time you handled a difficult customer or client.'),
('mock', 'What does success look like to you in this role?'),
('mock', 'Tell me about a time you worked with a team from a different culture or background.'),
('mock', 'How do you approach setting goals for yourself professionally?'),
('mock', 'Describe a time when you had to balance multiple priorities and how you coped.'),
('mock', 'Tell me about a time you received positive feedback that made a real difference to you.'),
('mock', 'How do you stay motivated when working on a long or repetitive project?'),
('mock', 'Describe a moment when you showed creativity to solve a problem at work.'),
('mock', 'Tell me about a time your idea was rejected and how you responded.'),
('mock', 'What is one thing you would change about your last job and why?');

-- ═══════════════════════════════════════════════════════════════
--  PROFESSIONAL SMALL TALK QUESTIONS — 50
-- ═══════════════════════════════════════════════════════════════
INSERT INTO questions (type, question) VALUES
('smalltalk', 'How has your week been going so far?'),
('smalltalk', 'Did you have a good weekend? What did you get up to?'),
('smalltalk', 'Have you been working on any interesting projects lately?'),
('smalltalk', 'What do you enjoy doing outside of work?'),
('smalltalk', 'Have you travelled anywhere interesting recently?'),
('smalltalk', 'What kind of industry events or conferences do you attend?'),
('smalltalk', 'Have you read any good books or listened to any podcasts lately?'),
('smalltalk', 'How long have you been working in your current role?'),
('smalltalk', 'What got you interested in your field of work?'),
('smalltalk', 'What are you looking forward to at the end of the workday today?'),
('smalltalk', 'Do you have any big plans coming up in the next few months?'),
('smalltalk', 'How are you finding the pace at work these days?'),
('smalltalk', 'What is one skill you have been trying to develop recently?'),
('smalltalk', 'Do you prefer remote work or working from the office, and why?'),
('smalltalk', 'What is the best professional advice you have ever received?'),
('smalltalk', 'Have you tried any new restaurants or cafes lately?'),
('smalltalk', 'Are you working on anything exciting outside of your main role?'),
('smalltalk', 'What is one thing that made you smile at work this week?'),
('smalltalk', 'How do you like to unwind after a long day at work?'),
('smalltalk', 'Have you picked up any new hobbies or interests recently?'),
('smalltalk', 'What is a city or country you would love to visit for work or leisure?'),
('smalltalk', 'Do you follow any sports teams or enjoy any sporting activities?'),
('smalltalk', 'What has been the highlight of your month so far?'),
('smalltalk', 'Are there any tools or apps you have recently started using that you love?'),
('smalltalk', 'What is your favourite way to recharge over a weekend?'),
('smalltalk', 'Have you attended any interesting workshops or training sessions recently?'),
('smalltalk', 'What is one goal you are working towards this year, professionally or personally?'),
('smalltalk', 'Do you prefer morning meetings or afternoon meetings, and why?'),
('smalltalk', 'Have you seen any good films or shows recently that you would recommend?'),
('smalltalk', 'What is something new you have learned in the past few weeks?'),
('smalltalk', 'How do you prefer to start your mornings before work?'),
('smalltalk', 'Is there a project or initiative at work that you are really excited about?'),
('smalltalk', 'What is your go-to way to stay focused during a busy workday?'),
('smalltalk', 'Have you connected with anyone new professionally recently?'),
('smalltalk', 'What has been your biggest learning from working in your current role?'),
('smalltalk', 'Do you have a favourite quote or piece of advice that guides you?'),
('smalltalk', 'Are you planning to attend any industry events or webinars soon?'),
('smalltalk', 'What is one thing about your job that you genuinely enjoy?'),
('smalltalk', 'How do you like to celebrate small wins at work?'),
('smalltalk', 'Have you tried anything new in your fitness or wellness routine lately?'),
('smalltalk', 'What kind of music or podcasts do you listen to while working?'),
('smalltalk', 'Is there a book you have been meaning to read but have not started yet?'),
('smalltalk', 'What is something at work you are looking forward to in the coming weeks?'),
('smalltalk', 'Do you prefer to work in silence or with background noise?'),
('smalltalk', 'Have you had any memorable conversations with colleagues or clients recently?'),
('smalltalk', 'What is one thing you would tell your younger professional self?'),
('smalltalk', 'How do you keep yourself energised during long working days?'),
('smalltalk', 'Is there a skill you wish you had developed earlier in your career?'),
('smalltalk', 'What is your favourite part of your daily work routine?'),
('smalltalk', 'Have you received any feedback recently that really stuck with you?');

-- ═══════════════════════════════════════════════════════════════
--  PRESENTATION PRACTICE QUESTIONS — 50
-- ═══════════════════════════════════════════════════════════════
INSERT INTO questions (type, question) VALUES
('presentation', 'Give a 60-second introduction of yourself to a hiring manager.'),
('presentation', 'Present your greatest professional achievement in two minutes.'),
('presentation', 'Pitch a new product idea to a room of investors in two minutes.'),
('presentation', 'Explain a complex topic in your field to a non-expert audience.'),
('presentation', 'Describe your vision for your career in the next three to five years.'),
('presentation', 'Present the key highlights from a project you recently completed.'),
('presentation', 'Make a case for why your team deserves additional budget or resources.'),
('presentation', 'Summarize a recent industry trend and its impact on your work.'),
('presentation', 'Introduce a new process improvement to your team.'),
('presentation', 'Close a sales pitch by addressing a client concern about price.'),
('presentation', 'Present a SWOT analysis of your department or organisation.'),
('presentation', 'Deliver constructive feedback to a team member about an area for improvement.'),
('presentation', 'Motivate your team at the start of a challenging quarter.'),
('presentation', 'Present your personal brand statement to a professional networking group.'),
('presentation', 'Explain why you are the right candidate for a promotion.'),
('presentation', 'Pitch a cost-saving initiative to senior management.'),
('presentation', 'Introduce yourself at a professional networking event in 90 seconds.'),
('presentation', 'Present a plan to improve customer satisfaction in your department.'),
('presentation', 'Give a progress update on a long-running project to your stakeholders.'),
('presentation', 'Explain the benefits of a new technology tool to a sceptical team.'),
('presentation', 'Present a risk assessment for a project you are about to start.'),
('presentation', 'Deliver a training session introduction on a topic you know well.'),
('presentation', 'Make the case for hiring a new team member to your manager.'),
('presentation', 'Propose a new partnership or collaboration idea to a potential partner.'),
('presentation', 'Summarize the key takeaways from a conference you attended.'),
('presentation', 'Present a competitor analysis to your marketing or strategy team.'),
('presentation', 'Pitch an idea to improve employee wellbeing in your organisation.'),
('presentation', 'Introduce a new company policy to your team and explain the reasons for it.'),
('presentation', 'Give a one-minute elevator pitch for your business or department.'),
('presentation', 'Explain your problem-solving approach using a recent example.'),
('presentation', 'Present a customer success story to your sales team.'),
('presentation', 'Propose a flexible working policy to your management team.'),
('presentation', 'Deliver an update on a delayed project and explain the path forward.'),
('presentation', 'Introduce a new team member to the rest of the organisation.'),
('presentation', 'Present your personal development plan for the next year to your manager.'),
('presentation', 'Make a case for expanding into a new market or geography.'),
('presentation', 'Deliver a closing statement at the end of an important client meeting.'),
('presentation', 'Present the results of a survey or research project to your team.'),
('presentation', 'Explain how your team plans to handle a crisis or unexpected event.'),
('presentation', 'Pitch a sustainability or social responsibility initiative to leadership.'),
('presentation', 'Present a product roadmap to a group of stakeholders.'),
('presentation', 'Describe your team's culture and working style to a potential new hire.'),
('presentation', 'Give a speech to thank your team after completing a major project.'),
('presentation', 'Present three options to solve a business problem and recommend one.'),
('presentation', 'Explain your company's mission and values to a group of new employees.'),
('presentation', 'Deliver a mid-year review of your team's goals and progress.'),
('presentation', 'Present a proposal to reduce operational costs without cutting quality.'),
('presentation', 'Give a 90-second summary of your expertise to a potential client.'),
('presentation', 'Explain why a project failed and what the team will do differently next time.');
